---
output:
  html_document: default
  pdf_document: default
---

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

```{r}
#RQ: Does domain-specifical movement behaviour profile membership mediate the relationship between socioeconomic position and socio-emotional outcomes in children?
##Simple mediation for females
```

```{r include=FALSE}
# Install and open appropriate libraries
library(medflex)
library(dplyr)
library(haven)
```

```{r}
# Load female dataset from Study 2, LSAC wave 6 data, and LSAC wave 8 data
load(file = "Z:/LSAC dataset/Study_2/Study_2/df_females_domsp_weekday.RData")
lsac_wave6 <- read_sas("Z:/LSAC dataset/General Release/Survey data/SAS/lsacgrb10.sas7bdat")
lsac_wave8 <- read_sas("Z:/LSAC dataset/General Release/Survey data/SAS/lsacgrb14.sas7bdat")
```

```{r}
# Select relevant columns from male dataset (hicid, profile membership, age, remoteness, Indigenous status, SEP)
relevant_female_data <- df_female_domsp_weekday %>%
  select(hicid, model4_trajectory_assignments, Age, Remoteness, Indigenous, SEP)

# Select relevant columns from LSAC wave 6 (SEIFA varialbes), parents living at home, parent mental health, parent ethnicity)
wave_6_relevant_data <- lsac_wave6 %>%
  select(hicid, fcnfsad2d, fcnfsda2d, fcnfser2d, fcnfseo2d, fmoth, ffath, fsc13a1i, zf09fm, zf09ff) 
# Update column names to make sense
colnames(wave_6_relevant_data)[2:10] <- c("adv", "dis", "resources", "education_occupation", "mother_home", "father_home", "mental_health", "mother_race", "father_race")

# Select relevant columns from LSAC Wave 8 (SDQ results)
wave_8_relevant_data <- lsac_wave8 %>%
  select(hicid, hapsoc:hasdqtb) 
# Update column names to make sense
colnames(wave_8_relevant_data)[2:7] <- c("prosocial", "hyperactivity", "emotional", "peer", "conduct", "total")

# Combine columns to make new dataset
domsp_wave6 <- inner_join(relevant_female_data, wave_6_relevant_data, by = "hicid")
df_females <- inner_join(domsp_wave6, wave_8_relevant_data, by = "hicid") 

#Take out participants with missing covariate data 
colSums(df_females < -8)
#1 missing mental health, 7 missing mother race, 115 missing father race 
df_females <- df_females[!(df_females$mental_health == -9), ]
df_females <- df_females[!(df_females$mother_race == -9), ]
df_females <- df_females[!(df_females$father_race == -9), ]

# Check dataframe for missing data reported as N/A 
colSums(is.na(df_females))
# 9 participants are missing SDQ data - this accounts for <1% of data and this information is essential for data anlaysis - therefore these participants will be removed from the dataset
df_females_na_removed <- na.omit(df_females)
```

```{r}
#Reduce mother and father race to 1 digit and convert to factor (2 digits caused the code to break)
df_females_na_removed$mother_race <- substr(df_females_na_removed$mother_race, 1, 1) %>% 
  as.factor()
df_females_na_removed$father_race <- substr(df_females_na_removed$father_race, 1, 1) %>% 
  as.factor()

# Covert relevant columns to factors 
factor_columns <- c(2,4:5,7:13)
for (x in factor_columns) {
  name <- colnames(df_females_na_removed[,x])
  df_females_na_removed[[name]] <- as.factor(df_females_na_removed[[name]])
}

#Scale all socio-emotional outcome variables 
df_females_na_removed[,16:21] <- scale(df_females_na_removed[,16:21])

```

```{r}
#Run loop for all socio-emotional variables 
for (x in 16:ncol(df_females_na_removed)) {
  name <- colnames(df_females_na_removed[,x])
  assign("objectname", (paste(name,"~",("SEP + model4_trajectory_assignments + Remoteness + Indigenous + adv + dis + resources + education_occupation + mother_home + father_home + mental_health + mother_race + father_race"))))
  expData <- assign(paste0("expData_", name), neImpute(objectname, data = df_females_na_removed))
  assign("model", (paste(name,"~",("SEP0 + SEP1 + Remoteness + Indigenous + adv + dis + resources + education_occupation + mother_home + father_home + mental_health + mother_race + father_race"))))
  outcome_results <- assign(paste0("ne_", name), neModel(model, expData = expData, se = "robust"))
  assign(paste0("effdecomp_", name), neEffdecomp(outcome_results))
}

```

```{r}
#Check results for mediation 
summary(effdecomp_prosocial)
#No mediation for prosocialtiy 
```

```{r}
summary(effdecomp_hyperactivity)
#No mediation for hyperactivity 
```

```{r}
summary(effdecomp_emotional)
#No mediation for emotional problems 
```

```{r}
summary(effdecomp_peer)
#No mediation for peer problems 
```

```{r}
summary(effdecomp_conduct)
#No mediation for conduct problems 
```

```{r}
summary(effdecomp_total)
#No mediation for total strengths and difficulties 
```


